### ISSUE TITLE
Lutris gui loads 

### ISSUE THREAD

**Issue by lefty420** [RobLoach/lutris-kodi-addon#25] opened 2017-08-03 12:57 UTC
Hey guys awesome work with the addon.  I don't know when it happened but now lutris gui loads after I launch a game and doesn't close after exiting the game. Is the common?

**Comment by RobLoach** [comment] 2017-08-03 14:30
Lutris issue is over at https://github.com/lutris/lutris/issues/578

**Comment by solbero** [comment] 2017-08-03 16:09
Duplicate of https://github.com/RobLoach/lutris-kodi-addon/issues/14.

**Comment by RobLoach** [comment] 2018-04-10 17:12
@hzeroo has been doing an awesome job cleaning this up in Lutris upstream :+1:

**Closed by RobLoach** 2018-04-10 17:12 UTC
Labels: duplicate
